services:
  # Desktops virtual
  desktop-01:
    image: lscr.io/linuxserver/rdesktop:ubuntu-xfce
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    shm_size: "1gb"
    volumes:
      - ./desktop/desktop-01:/config
    ports:
      - 3389:3389

  # Guacamole
  guacd:
    image: guacamole/guacd:1.5.2
  guacamole:
    image: guacamole/guacamole:1.5.2
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - MYSQL_HOSTNAME=mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=guacamole
    ports:
      - 8080:8080
    depends_on:
      - guacd
      - mariadb

  # Banco de dados
  mariadb:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=guacamole
    volumes:
      - ./database/datadir:/var/lib/mysql
      - ./database/guacamole.sql:/docker-entrypoint-initdb.d/guacamole.sql